apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
spec:
  replicas: 1
  selector:
    matchLabels:
      name: master
  template:
    metadata:
      labels:
        name: master
    spec:
      containers:
      - name: master
        image: master:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 6000
            name: flask