# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|
    config.vm.define "master" do |cfg|
        cfg.vm.box = "sysnet4admin/CentOS-k8s"
        cfg.vm.provider "virtualbox" do |vb|
            vb.name = "master"
            vb.cpus = 2
            vb.memory = 2048
            vb.customize ["modifyvm", :id, "--groups", "/master"]
        end
        cfg.vm.host_name = "master"
        cfg.vm.network "private_network", ip: "192.168.1.10"
        cfg.vm.network "forwarded_port", guest: 22, host: "60100", auto_correct: true, id: "ssh"
        cfg.vm.synced_folder "../data", "/vagrant", disabled: true
        cfg.vm.provision "shell", path: "swap_disabled.sh"
        cfg.vm.provision "shell", path: "installation.sh"
    end
end
