apiVersion: apps/v1
kind: Deployment
metadata:
  name: mypython
spec:
  replicas: 3
  selector:
    matchLabels:
      name: mypython
  template:
    metadata:
      labels:
        name: mypython
    spec:
      containers:
      - name: mypython
        image: rehoosa/mypython:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
            name: flask
---
apiVersion: v1
kind: Service
metadata:
  name: mypython-svc
spec:
  selector:
      name: mypython
  ports:
    - name: service
      port: 80
      targetPort: 5000
  type: LoadBalancer